### ISSUE TITLE
 unknown command ".network.genesisProfile" for "yq"

### ISSUE THREAD

**Issue by zillerium** [APGGroeiFabriek/PIVT#12]
unknown command ".network.genesisProfile" for "yq"

I am getting this error out of the box when I run - 
./init.sh ./samples/simple/ ./samples/chaincode/

I am unsure why the yq is failing here.

**Comment by gWOLF3** [comment]
you may not be using the correct version of yq:

you need https://yq.readthedocs.io/en/latest/. 

if you are on a macOS, make sure you use `brew install python-yq` instead of `brew install yq`. they have different command syntax

**Comment by raftAtGit** [comment]
right, exactly, it must be incorrect version of `yq`

check the [requirements](https://github.com/APGGroeiFabriek/PIVT#requirements) section for correct version and where from to install

**Comment by gWOLF3** [comment]
@zillerium 

if your issue has been resolved, please **/close** this issue.

**Comment by zillerium** [comment]
I have 2.4 but I have installed via pip. Is there something to change for pip here?

**Comment by raftAtGit** [comment]
try using version  2.6+ as mentioned in the [requirements](https://github.com/APGGroeiFabriek/PIVT#requirements)

**Comment by arya0618** [comment]
I am getting the same error with **yq** version 3.6. I am working on ubuntu 18.04.

**Comment by raftAtGit** [comment]
possibly there is a confusion in your PATH variable, i.e the `init.sh` script is using an older version of `yq`
