### ISSUE TITLE
how to launch pod for fabric CLI?

### ISSUE THREAD

**Issue by Shubham-koli** [APGGroeiFabriek/PIVT#17]
I am new to Kubernetes Deployment.the current setup does an excellent job at launching nodes but I was wondering how do I launch the pod for fabric CLI?

**Comment by raftAtGit** [comment]
you dont need a CLI pod actually. just attach to peer pods do what you want there. 

`admin certs` are mounted to peer pods for debugging but not used by default. if you need admin rights, run this command before any `peer` command

```
export CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/admin-msp/
```

**Comment by Shubham-koli** [comment]
![Screenshot from 2019-10-31 18-07-46](https://user-images.githubusercontent.com/37935825/67947321-6b808200-fc09-11e9-99c2-6537c6fe8fbb.png)
I've tried it and unfortunately, It is not working for me.
I get the error of 

> Error: error getting endorser client for channel: endorser client failed to connect to peer0.nevergreen.nl:7051: failed to create new connection: context deadline exceeded
These are my orderer logs 
![Screenshot from 2019-10-31 18-11-04](https://user-images.githubusercontent.com/37935825/67947534-dcc03500-fc09-11e9-9deb-4399d9388158.png)
And I don't know why I am also getting TLS  bad certificate error.
![Screenshot from 2019-10-31 18-11-39](https://user-images.githubusercontent.com/37935825/67947605-ffeae480-fc09-11e9-8c2d-cd90041bdde4.png)

**Comment by raftAtGit** [comment]
that's weird. just works fine for me. is that `Raft` orderer?
what is the output of this command inside peer?
```
cat /etc/hosts
```

ps: `peer channel list` command does not need admin rights, btw

**Comment by Shubham-koli** [comment]
![Screenshot from 2019-10-31 18-30-55](https://user-images.githubusercontent.com/37935825/67948897-acc66100-fc0c-11e9-87ab-09d8fb3fae94.png)
Yes, you are right. I am doing experiments on `Raft` orderer. 
This is the output for 

> cat /etc/hosts

**Comment by raftAtGit** [comment]
and this one?
```
echo $CORE_PEER_TLS_ENABLED
```

**Comment by Shubham-koli** [comment]
> root@hlf-peer--nevergreen--peer0-0:/# echo $CORE_PEER_TLS_ENABLED
> true

**Comment by Shubham-koli** [comment]
Ummm I believe this is not a temporary network issue, cause I've restarted the network 3 times. still, it gives me the same error. I will clear everything on Kubernetes and try again. let's see if it works.

**Comment by raftAtGit** [comment]
if still fails, one thing you can try is, add a `sleep loop` after [this line](https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/channel-flow/templates/channel-workflow.yaml#L286).

obviously Argo pods can access to peers. you can exec into Argo pod, try same command there, and if it succeeds compare environment variables with the peer.

**Comment by Shubham-koli** [comment]
okay sure. I will try it and update you!

**Comment by Shubham-koli** [comment]
okay, so I deleted the existing cluster and restarted minikube.
successfully executed all the steps.
still, I'm getting TLS error. 

> 2019-11-01 09:03:55.684 UTC [core.comm] ServerHandshake -> ERRO 0fe TLS handshake failed with error remote error: tls: bad certificate server=PeerServer remoteaddress=172.17.0.13:5973


![Screenshot from 2019-11-01 14-50-47](https://user-images.githubusercontent.com/37935825/68014983-01261b00-fcb7-11e9-88cb-d3ad430b36ba.png)

I am assuming that if my peers have bad certificates they shouldn't be able to communicate with any node in the network right? 
In my case my peers are working fine except the ` tls: bad certificate server` and `Error: error getting endorser client for channel: endorser client failed to connect to peer0.aptalkarga.tr:7051: failed to create a new connection: context deadline exceeded` part.
what could be the reason causing such behavior?

My orderers are clean and they don't get ` tls: bad certificate server` error.
![Screenshot from 2019-11-01 14-53-13](https://user-images.githubusercontent.com/37935825/68015088-582bf000-fcb7-11e9-8d9d-8545cf43c4bc.png)

**Comment by raftAtGit** [comment]
that's really weird! it just works here.

and you are right, if certificates are bad, they cannot communicate to each other and argo flow should fail too.

what is the output of these command:
```
peer version
env | grep CORE_
```

**Comment by raftAtGit** [comment]
also provide the output of these command please:
```
export FABRIC_LOGGING_SPEC=debug
peer channel list
```

**Comment by raftAtGit** [comment]
no worries, we love spooky Halloweens :)

which Kubernetes is that? 

yea, looks like this is not TLS issue. try these please:

```
curl peer0.nevergreen.nl:7051
curl hlf-peer--nevergreen--peer0:7051

curl <service cluster IP>:7051
curl <pod cluster IP>:7051
```
you can get cluster IP's of service and pod with the command below:
```
kubectl -n hlf get svc | grep hlf-peer--nevergreen--peer0
kubectl -n hlf get pod -o wide | grep hlf-peer--nevergreen--peer0
```

**Comment by Shubham-koli** [comment]
I tried to get the cluster IP's by the commands you suggested but they returned no output. you can see it in this screenshot
 
![Screenshot from 2019-11-04 18-06-13](https://user-images.githubusercontent.com/37935825/68121479-de516c00-ff2d-11e9-9694-84075117dd3a.png)


then I started a busybox and executed the same commands, after executing the commands and following was the output.

> / # curl -o - hlf-peer--nevergreen--peer0:7051

/ # curl peer0.nevergreen.nl:7051
curl: (6) Could not resolve host: peer0.nevergreen.nl
/ # curl 10.96.181.27:7051
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
/ # curl -o - 10.96.181.27:7051

/ # curl 172.17.0.19:7051
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
/ # curl -o - 172.17.0.19:7051

/ # 


![Screenshot from 2019-11-04 18-01-52](https://user-images.githubusercontent.com/37935825/68121325-7733b780-ff2d-11e9-9f5f-09b0b4f04f27.png)

**Comment by raftAtGit** [comment]
I meant running `curl` commands inside peer. running in a `busybox` pod is not exactly the same.

and which Kubernetes platform is that? Minikube?

**Comment by Shubham-koli** [comment]
well, I can't run curl inside a peer. neither can download it. 

Yes, I am using minikube some details are as follows.

> minikube version: v1.4.0
> 
> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
> 
> Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
>

**Comment by raftAtGit** [comment]
you can install curl with this command inside peer
```
apt-get update && apt-get install curl -y
```

**Comment by Shubham-koli** [comment]
Woah, okay.
I can curl every other node including orderer.

> root@hlf-peer--atlantis--peer0-0:/# curl peer0.nevergreen.nl:7051

root@hlf-peer--atlantis--peer0-0:/# curl hlf-peer--nevergreen--peer0:7051

root@hlf-peer--atlantis--peer0-0:/# curl peer0.nevergreen.nl:7051

root@hlf-peer--atlantis--peer0-0:/# curl hlf-peer--nevergreen--peer0:7051

root@hlf-peer--atlantis--peer0-0:/# curl 10.96.181.27:7051

root@hlf-peer--atlantis--peer0-0:/# curl 10.106.179.135:7051

![Screenshot from 2019-11-04 18-59-39](https://user-images.githubusercontent.com/37935825/68124406-53746f80-ff35-11e9-896f-a8664e23f60b.png)

One interesting thing, I can not curl local peer (the peer, which I'm using to ping other peers) using it's `name` or `service cluster IP` but I can ping it using it's `pod cluster IP`

> root@hlf-peer--atlantis--peer0-0:/# peer channel list
Error: error getting endorser client for channel: endorser client failed to connect to peer0.atlantis.com:7051: failed to create new connection: context deadline exceeded
root@hlf-peer--atlantis--peer0-0:/# curl peer0.atlantis.com:7051
^C
root@hlf-peer--atlantis--peer0-0:/# curl 10.105.76.162:7051
^C
root@hlf-peer--atlantis--peer0-0:/# curl 172.17.0.14:7051

root@hlf-peer--atlantis--peer0-0:/# 



![Screenshot from 2019-11-04 19-07-44](https://user-images.githubusercontent.com/37935825/68124960-89662380-ff36-11e9-9b82-331ae82c2228.png)

**Comment by raftAtGit** [comment]
ah, looks like you hit this [Minikube issue](https://github.com/kubernetes/minikube/issues/1568) :/

so, as a workaround, when not using TLS, you can set below environment variable
```
export CORE_PEER_ADDRESS=127.0.0.1:7051
```

for TLS (and hence Raft orderer), save [this file ](https://raft-fabric-kube.s3-eu-west-1.amazonaws.com/patches/peer-cli-deployment.yaml) to `hlf-kube/templates/` folder and re-launch stuff or make a Helm upgrade.

it will create a CLI Pod for each peer configured for that peer

**Comment by Shubham-koli** [comment]
So I copied the file to the `hlf-kube/template` and relaunched network. but I ran into this Error.

> Error: render error in "hlf-kube/templates/peer-cli-deployment.yaml": template: hlf-kube/templates/peer-cli-deployment.yaml:171:18: executing "hlf-kube/templates/peer-cli-deployment.yaml" at <$.Values.peer.metrics.enabled>: nil pointer evaluating interface {}.enabled

Well, for quick error resolution I removed lines 170-174 :P
but these issues seem to follow me wherever I go.
so I ran into new issue

> Warning  FailedMount  57s (x12 over 9m11s)    kubelet, minikube  MountVolume.SetUp failed for volume "peer-msp" : references non-existent secret key: config.yaml

![Screenshot from 2019-11-05 11-25-22](https://user-images.githubusercontent.com/37935825/68182596-c75b5a00-ffbf-11e9-9d05-0c15c7a69423.png)

**Comment by Shubham-koli** [comment]
@raftAtGit can you please point me in the direction on how to resolve this issue?

**Comment by raftAtGit** [comment]
sorry, I just forgot our internal repo is a bit ahead of this public repo. 

re-download the file please. hopefully it should be fine now.

**Comment by Shubham-koli** [comment]
holy shit it worked !!!!!

I can't thank you enough!!!

**Comment by Shubham-koli** [comment]
Commenting here for future reference, 
if you start the `CLI` pods before creating `channels` and chaincodes. your `Argo` workflow for creating channels and chaincodes will give errors.
so start the `CLI` pods after you've populated the network with `channels` and `chaincodes`.

**Comment by raftAtGit** [comment]
that is also unexpected. what error do you get?

**Comment by Shubham-koli** [comment]
oh no sorry error was at my side. I am not able to reproduce the error but everything works fine!
