### ISSUE TITLE
Not able to attach persistent volumes to the containers.

### ISSUE THREAD

**Issue by Shubham-koli** [APGGroeiFabriek/PIVT#18]
I am using Minikube for my local Kubernetes cluster. 
Minikube: 1.4.0
kubectl : 1.15.3
kubernetes: 1.16.0

I was trying to add new peer organizations to an existing network, where I ran into this issue where persistent volumes are not being attached to the containers. Due to this peer and orderer pods are always in the pending state.

`Info about the pvc`

> Warning  ProvisioningFailed  3m14s (x122 over 33m)  persistentvolume-controller  storageclass.storage.k8s.io "default" not found

![Screenshot from 2019-11-07 11-24-24](https://user-images.githubusercontent.com/37935825/68367727-58ffce80-015c-11ea-8e6f-90c471e043a7.png)

`Info about the pod`

> Warning  FailedScheduling  <unknown>  default-scheduler  pod has unbound immediate PersistentVolumeClaims

![Screenshot from 2019-11-07 11-23-54](https://user-images.githubusercontent.com/37935825/68365695-65cdf380-0157-11ea-90a1-83fd2889be86.png)

**Comment by raftAtGit** [comment]
what is the output of this command?
```
kubectl get StorageClass
```

**Comment by Shubham-koli** [comment]
`kubectl get StorageClass`
The output of this command is as follows.
```
NAME                 PROVISIONER                AGE
standard (default)   k8s.io/minikube-hostpath   24h

```
`kubectl describe StorageClass standard `
The output of this command is as follows.
```
Name:                  standard
IsDefaultClass:        Yes
Annotations:           storageclass.kubernetes.io/is-default-class=true
Provisioner:           k8s.io/minikube-hostpath
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

```

The issue can only be seen on minikube. 
everything works fine on the Kubernetes cluster created by kops.

**Comment by raftAtGit** [comment]
your `StorageClass`  name is `standard`, not `default`. you need to pass this parameter when launching the network:
```
--set persistence.storageClass=standard
```
or edit the value in `hlf-kube/values.yaml` file

**Comment by Shubham-koli** [comment]
`helm install ./hlf-kube --name hlf-kube -f samples/scaled-raft-tls/persistence.yaml -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/crypto-config.yaml --set peer.launchPods=false --set orderer.launchPods=false --set persistence.storageClass=standard`

is this correct?

**Comment by raftAtGit** [comment]
yup correct. actually in this case, put the value to `samples/scaled-raft-tls/persistence.yaml`, it's a good fit for there ;)
