### ISSUE TITLE
NPM issue deploying Node chaincode

### ISSUE THREAD

**Issue by jeffywu** [APGGroeiFabriek/PIVT#2]
Hi, I'm running into the following issue when trying to instantiate node chaincode in the release/0.7 example:

```
$ kubectl logs -f hlf-chaincodes-zb7mn-1171026065 main
....
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: Failed to generate platform-specific docker build: Error returned from build: 1 "npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/fabric-shim failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-13T20_13_10_140Z-debug.log
```

Looks like an issue resolving NPM? Have you seen this error before?

Also, I thought the first rule of blockchain club is "don't talk about blockchain club" :)

**Comment by raftAtGit** [comment]
Yea, this is reported before. Most possibly chaincode containers created out of knowledge of Kubernetes cannot access internet.

Is that AWS EKS? If so, see this issue for the reason and the fix:
https://github.com/APGGroeiFabriek/PIVT/issues/1

If it's not, still see that issue for how to handle this. And please report your fix in that case :)

For BlockChain club, haha, true for sure, it will help not using it ;)

**Comment by jeffywu** [comment]
Duplicate of #1
