### ISSUE TITLE
I can't Invoke function

### ISSUE THREAD

**Issue by softreform** [APGGroeiFabriek/PIVT#20]
peer chaincode invoke  -C common -n very-simple -c '{"Function":"IndividualContract:createUser","Args":["IndividualContract:createUser","abc"]}'

I gave ERROR
Error: endorsement failure during invoke. response: status:500 message:"transaction returned with failure: Received unknown function IndividualContract:createUser invocation"

Who can help with it ?

**Comment by raftAtGit** [comment]
I dont know, the error is clear actually, your chaincode doesnt have that function

**Comment by softreform** [comment]
Thanks for answer. My chaincode generated by IBM Blockchain Platform ( for VScode ) and are very simple to test HLF.
Chaincode can be written using fabric-shim ( low level programming ) or fabric-contract-api.

Chaincodes written in fabric-contract-api have Classes and all function looks like 
MyticheContract:createMytiche
Something wrong to initiate & invoke chaincodes written in fabric-contract-api.
I attached auto-generated & tested ( worked ) simple chaincode , written in fabric-contract-api
Could you please check it ?

[mytiche.zip](https://github.com/APGGroeiFabriek/PIVT/files/3842905/mytiche.zip)

I have this mistake :
![image](https://user-images.githubusercontent.com/54245293/68794164-2459ae80-0657-11ea-8f54-bf99eb31b8ec.png)

**Comment by raftAtGit** [comment]
please `ssh` into your VM's and run the command below and try again
```
docker rmi --force $(docker images --format '{{ .Repository }}' | grep "dev-peer" )
```

**Comment by softreform** [comment]
Hi. Very thanks for the answer. I removed lot of images. 
I set invoke to false in chaincode-flow. 
But simple TypeScript generated chaincode don't want to instantiate now.
![image](https://user-images.githubusercontent.com/54245293/68855995-2881dc80-06e8-11ea-9b3a-310bda9196b8.png)

Any idea why TypeScript chaincode don't want to insnatiate ?
![image](https://user-images.githubusercontent.com/54245293/68856150-7f87b180-06e8-11ea-874f-22c67ea13e5a.png)

**Comment by raftAtGit** [comment]
looks like TypeScript chaincode doesnt have an empty constructor. Our flow [tries to use](https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/chaincode-flow/templates/chaincodes-workflow.yaml#L337) the empty constructor

**Comment by softreform** [comment]
Very thanks. I'll try to change that raw and send variable with some other --ctor

**Comment by softreform** [comment]
Hi all. Very thanks for the help. I tried to change invoke-command for TypeScript contact basd on fabric-contract-api ( not on fabric-shim)
Could someone help me with that mistake? Invoke doesn't see the Functions of my chaincode.
I tryied  to use this --ctor 
![image](https://user-images.githubusercontent.com/54245293/69009108-0ba10f80-095b-11ea-88bc-7648e5a54c06.png)

And ger Error 500 (((
![image](https://user-images.githubusercontent.com/54245293/69009088-cbda2800-095a-11ea-9791-1abbf0d98607.png)

**Comment by raftAtGit** [comment]
`--ctor '{"Function":"IndividualContract:createUser","Args":["invokeFirstUser"]}'`

you are trying invoke a method, you should only pass the constructor args here. whatever they are. have a [look at](https://fabric-shim.github.io/release-1.4/tutorial-using-contractinterface.html)
