### ISSUE TITLE
Invoking chaincoide within peer container

### ISSUE THREAD

**Issue by marcelloromani** [APGGroeiFabriek/PIVT#23]
I am trying to execute ```peer chaincode invoke``` from within `peer0.aptalkarga.tr`

I am trying to reproduce the same environemnt that the chaincode workflow `invoke-chaincode--idv--common--Karga--peer0`

The only change I need to make is related to `/hlf_config/orderer-tlsca/tlscacert.pem`: since the peer pod doesn't have that mount, I extracted the content of the secret `hlf-orderer--groeifabriek-tlsca` and copied the resulting `tlscacert.pem` into `/tmp/tlscacert.pem` in the peer container.
I then changed the command line using `--cafile /tmp/tlscacert.pem`

The result I get is:
```
root@hlf-peer--karga--peer0-0:/# peer chaincode invoke -C common -c peer chaincode invoke -C common -o orderer0.groeifabriek.nl:7050 -n mycc -c '{"function":"myfunc","Args":[""]}' --tls --cafile /tmp/tlscacert.pem
Error: error endorsing invoke: rpc error: code = Unknown desc = Failed evaluating policy on signed data during check policy on channel [common] with policy [/Channel/Application/Writers]: [implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Writers' sub-policies to be satisfied] - proposal response: <nil>
```

It seems that the peer is not a writer.

Since the workflow step succeds, I am assuming that I'm doing something wrong in replicating the same environment as the workflow step...

**Comment by marcelloromani** [comment]
I tried calling the `invoke` from the Atlantis org but got the same error

```root@hlf-peer--atlantis--peer0-0:/# peer chaincode invoke -C common -n mycc -c peer chaincode invoke -C common -o orderer0.groeifabriek.nl:7050 -c '{"function":"myfunc","Args":[""]}' --tls --cafile /tmp/tlscacert.pem
Error: error endorsing invoke: rpc error: code = Unknown desc = Failed evaluating policy on signed data during check policy on channel [common] with policy [/Channel/Application/Writers]: [implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Writers' sub-policies to be satisfied] - proposal response: <nil>```

**Comment by marcelloromani** [comment]
I think this might be related to this other error I see: if I try to list the installed chaincode I get 'this identity is not an admin"

```
root@hlf-peer--karga--peer0-0:~# peer chaincode list --installed
Error: Bad response: 500 - access denied for [getinstalledchaincodes]: Failed verifying that proposal's creator satisfies local MSP principal during channelless check policy with policy [Admins]: [This identity is not an admin]
```

**Comment by marcelloromani** [comment]
We were able to successfullly invoke the chaincode by setting:

```
CORE_PEER_MSPCONFIGPATH=/etc/hyperledeger/fabric/admin-msp
```

**Comment by raftAtGit** [comment]
right, by [default configuration](https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/samples/simple/configtx.yaml#L59) only `admins` and `clients` can write. not the `peers`

**Comment by the-inevitable** [comment]
Hi @marcelloromani ! It seems like I'm facing the same issue at the moment. I don't really understand how exactly did you fix it? 

Where exactly do I have to set this setting `CORE_PEER_MSPCONFIGPATH=/etc/hyperledeger/fabric/admin-msp` ?

**Comment by the-inevitable** [comment]
@raftAtGit hey there,

Maybe you could help me with it? I'm trying to invoke a chaincode method from within a peer container and getting an error saying `Error: error endorsing invoke: rpc error: code = Unknown desc = Failed evaluating policy on signed data during check policy on channel [common] with policy [/Channel/Application/Writers]: [implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Writers' sub-policies to be satisfied] - proposal response: <nil>`

How should invoke a chaincode method correctly? Do I have to restart anything after any changes made?

Thank you in advance

**Comment by marcelloromani** [comment]
@the-inevitable if I remember correctly there's a configmap where the environment variables are set.

**Comment by the-inevitable** [comment]
@raftAtGit @marcelloromani great! Thank you a lot!
`export CORE_PEER_MSPCONFIGPATH=/etc/hyperldeger/fabric/admin-msp` worked fine.

But I guess that is not a best practice. For example, what if I want to update channel BatchSize.AbsoluteMaxBytes - I can't do that from a peer, or can I? 

How would one initiate such an update anyway?

This will be extremely useful knowledge! Thank you!

**Comment by raftAtGit** [comment]
to make a channel update, you need orderer (system) channel admins, regular peer organization admins wont help.

see [updating-channel-configuration](https://github.com/APGGroeiFabriek/PIVT#updating-channel-configuration) for more details
