### ISSUE TITLE
when is the next release?

### ISSUE THREAD

**Issue by Shubham-koli** [APGGroeiFabriek/PIVT#26]
I really want to thank you for creating this project. This project has really helped me and motivated me to learn Kubernetes and given a deep knowledge of fabric as well...
I wanted to ask you if you are planning on the next release. if yes then when?

Thank you.

**Comment by raftAtGit** [comment]
thanks for the nice words :)

release is just a marker. in particular release 0.7 was created to separate the home-built CLI tools usage. you can safely use the `master` branch, we are using it in our environments since long time without any issues.

**Comment by Shubham-koli** [comment]
Thank you for replying! yeah, I've been experimenting with it too. it is a piece of work! wonderful :)
