### ISSUE TITLE
Question: using Helm 3

### ISSUE THREAD

**Issue by palra** [APGGroeiFabriek/PIVT#29]
Awesome project! I just discovered it and I might be using it a lot, I won't hesitate giving feedback and PRs :)

It looks like the project is not ready for Helm 3. Is that something you have in mind? Or maybe it would require too much work to make it run with Helm?

**Comment by raftAtGit** [comment]
thank you for the kind words :)

we didnt try Helm 3 actually. for all the other stuff we use Helm 2.x. possibly at some point will be upgraded for Helm 3.x but no timeline yet.

what issues do exist with Helm 3?

**Comment by palra** [comment]
Helm 3 migration looks quite smooth : https://helm.sh/blog/migrate-from-helm-v2-to-helm-v3/
I could try to run it but I can't get the network working so I can't check if it's working :sweat_smile: 
Helm 3 would be really useful for namespacing, as with Helm 2 it's more difficult (or maybe impossible) to get the same charts running on different namespaces. I even had trouble installing a chart on a different namespace than the default one, but I think that it's just me messing un with the CLI flags. Not depending on Tiller anymore is a plus too.

**Comment by raftAtGit** [comment]
we actually run our Fabric network in a non-default namespace. so there is no issue there.

script files like `collect_host_aliases.sh` also excepts namespaces. this is not documented elsewhere I guess

**Comment by rpocase** [comment]
@palra Did you hit any specific issue? As far as I can tell, the only changes in our internal fork that I made specifically for helm 3 was moving `requirements.yaml` contents to `Chart.yaml`.

**Comment by palra** [comment]
Thanks for reaching out. I didn't progressed in that way, I was still stuck on my other issue. I think it's RBAC related, I must have messed up with the configuration. I'll tell you once I'll have time to focus on that.

**Comment by palra** [comment]
Finally, I could setup my own network using Helm 3, i didn't hit any specific issues. It works like a charm :)
