### ISSUE TITLE
Migrate collect_host_aliases to coredns

### ISSUE THREAD

**Issue by rpocase** [APGGroeiFabriek/PIVT#31]
I've finally gotten to a point where I care to migrate to a TLS backed orderer and found that the manual redeploy of host aliases would be a bit too inconvenient. With coredns being the recommended default DNS provider, this seemed like a good candidate for naming.

E.g., I use a variant of the following rewrite:

```
rewrite stop {
    name regex (orderer|peer)(\d+)\.(.*)\.k8s hlf-{1}--{3}--{1}{2}.default.svc.cluster.local
    answer name hlf-(orderer|peer)--(.*)--(orderer|peer)(\d+)\.default\.svc\.cluster\.local {1}{4}.{2}.k8s
}
```
In the above example I am using a consistent FQDN suffix (.k8s). To support multiple suffixes you could have multiple rewrite rules. This, of course, assumes your domain (e.g. atlantis, nevergreen, etc) are consistent. To make this work, I needed to change "aptalkarga" to "karga".

I suspect you could also route to the loadbalanced services instead (e.g. hlf-org-peer--karga) but I have yet to test this.

Lastly, the above assumes everything is deployed in the default namespace. Many clusters may be able to get away with dropping the "default.svc.cluster.local" requirements and allow DNS to route appropriately. A lot of this really just depends on your specific requirements.

**Comment by Shubham-koli** [comment]
does this mean we don't need to restart the pods every time we add new peer or organization?

**Comment by raftAtGit** [comment]
Interesting. 

@rpocase did you see this completed [pull request](https://github.com/APGGroeiFabriek/PIVT/pull/25)? it allows TLS without `actual domain names`. if you dont want to use `host aliases`, it might be more portable and convenient solution.

**Comment by rpocase** [comment]
> does this mean we don't need to restart the pods every time we add new peer or organization?

@Shubham-koli I'm not positive, but I would expect so. I haven't gone through the process of adding new peers or orgs. At the very least, you do not need the host_aliases dance, avoiding that hard requirement for multiple network deploys.

@raftAtGit I had not seen that PR. That definitely seems cleaner than coredns for a completely in-cluster network by a single organization, but may be less convenient if you had a network that spans several organizations (the HLF target use case). The `SANS` field does seem to provide the ability to have both the in-cluster and a FQDN name on the same cert, though.

Definitely open to other suggestions as long as it doesn't require multiple `hlf-kube` deploys just to get TLS functional :).

**Comment by raftAtGit** [comment]
@rpocase by “multiple organizations” I guess you mean networks spanning multiple Kubernetes clusters or at least some reside outside of Kubernetes cluster.  because the setup already spans multiple organizations.

anyway, for production scenarios, I believe hostAliases is the best and most flexible option. it might not just be much convenient for development, but not a big issue actually

not everyday we make a deployment and add new peer organizations

**Comment by rpocase** [comment]
Yep, that is what I mean by organizations. Truly separate organizations managing their own HLF members. 

Most of my time is spent working in development environments. I often tear these down multiple times a day. Adding additional latency to this process is fairly unacceptable.

For production use cases, long term, I expect we won't use exactly this setup anyway. This depends on the end decisions on how to deal with crypto. As far as I can tell, most HLF users highly recommend not using cryptogen in production for legitimate reasons. While convenient for dev, it really provides no strong sense of trust since everything is rooted in self-signed certs.

**Comment by raftAtGit** [comment]
check FAQ for usage of cryptogen, it’s not mandatory

**Comment by rpocase** [comment]
Going ahead and closing this since it seems out of vision with this repo. Mostly wanted to document a solution for this problem that works a bit better for me since it may be useful for others.
