### ISSUE TITLE
getting error unknown command ".ExternalPeerOrgs // empty" for "yq"

### ISSUE THREAD

**Issue by abhisamant7** [APGGroeiFabriek/PIVT#34]
Hi,

I am getting error when I am trying to run "./init.sh ./samples/simple/ ./samples/chaincode/" command for creating necessary stuff as mention in readme file.

system info:- Ubuntu 18.04
 yq version 3.1.2
jq version:- jq-1.5-1-a5b5cbe
helm version:- 2.16.2
agro version:v2.4.3

Please help me to resolve the issue. 

Thanks in advance

**Comment by raftAtGit** [comment]
how can I help you if you dont even tell what error you get!? :)

**Comment by abhisamant7** [comment]
Hi,

Sorry I had mention in header of issue I am getting as ".ExternalPeerOrgs // empty" for "yq" when  trying to run "./init.sh ./samples/simple/ ./samples/chaincode/" command

**Comment by raftAtGit** [comment]
himm, sorry didnt notice that.

looks like somehow you are using an incompatible version of `yq`. try installing it from the link mentioned in `requirements`

in general, `2.6.0 - 2.10.0` (latest when installed with `pip`) is known to work fine.

**Comment by abhisamant7** [comment]
yes you are right there is another software with same name which confused me.
I was trying to install using link which you have provide, however its giving error with python and pip.
but I resolve the issue thanks for the reply and help

**Comment by knagware9** [comment]
I have installed correct version of jq & yq from mentioned link but getting the same error

**Comment by knagware9** [comment]
@abhisamant7  how you solve it ? Please help

**Comment by raftAtGit** [comment]
well, looks like the `init.sh` script does not use the software you installed.

what are the outputs of these commands?
```
jq --version
yq --version
```

**Comment by chebyte** [comment]
@knagware9 I upgrade the command, cause I'm using new version of yq so it looks like this

````
externalPeerOrgs=$(yq r -c ./crypto-config.yaml 'ExternalPeerOrgs // empty')
````

````
externalOrdererOrgs=$(yq r -c ./crypto-config.yaml 'ExternalOrdererOrgs // empty')
````

````
    genesisProfile=$(yq r $config_file 'network.genesisProfile')
    systemChannelID=$(yq r $config_file 'network.systemChannelID')

````
