### ISSUE TITLE
Getting error while  launch the network

### ISSUE THREAD

**Issue by abhisamant7** [APGGroeiFabriek/PIVT#35]
Hi 

I am new to k8s and helm chart so I am facing issue while run the command which is in the readme file.
I am getting error as `"Error: release hlf-kube failed: namespaces "default" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "default"` when I am trying to launch the network using command 
`helm install ./hlf-kube --name hlf-kube -f samples/simple/network.yaml -f samples/simple/crypto-config.yaml
`
could you please help me this issue

thanks

**Comment by raftAtGit** [comment]
looks like there is a problem with your Helm installation

check [here](https://lmgtfy.com/?q=helm+namespaces+%22default%22+is+forbidden%3A+User+%22system%3Aserviceaccount%3Akube-system%3Adefault%22+cannot+get+resource+%22namespaces%22+in+API+group) ;)

**Comment by abhisamant7** [comment]
Hi Raft,

Thanks for the link I follow this links and its been solve the issue.

Great man

**Comment by abhisamant7** [comment]
Hi Raft,

Thanks for the link I follow this links and its been solve the issue.

Great man
