### ISSUE TITLE
issues while adding new peer org to the cross-cluster-raft.

### ISSUE THREAD

**Issue by Shubham-koli** [APGGroeiFabriek/PIVT#37]
First of all amazing work, thank you so much!
I was experimenting with the cross-cluster raft network. I have one cluster deployed on the `AWS` and the other one is on the `G-cloud` (both kops). (I've not deployed Nevergreen on cluster 3)
The deployed Fabric network works perfectly fine. Now I want to add the new peer organization into the cluster one.
I've deployed `crypto` to the cluster one. peers are running. successfully collected the `hostAliases`.
now while I'm running the` peer-org-flow/` I'm getting the following error.

```
ubuntu@ip-172-31-42-73:~/new/PIVT/fabric-kube$ helm template peer-org-flow/ -f samples/cross-cluster-raft-tls/cluster-one/configtx.yaml -f samples/cross-cluster-raft-tls/cluster-one/network.yaml -f samples/cross-cluster-raft-tls/cluster-one/crypto-config.yaml -f samples/cross-cluster-raft-tls/cluster-one/hostAliases.yaml | argo submit - --watch
2020/02/26 11:36:44 Failed to submit workflow: templates.peer-orgs.steps[0].consortiums templates.consortiums.steps[1].TheConsortium templates.consortium--TheConsortium.steps[1].consortium-org--Nevergreen templates.consortium-org--TheConsortium--Nevergreen.steps[1].add-org-to-consortium templates.add-org-to-consortium--TheConsortium--Nevergreen.steps[0].create-system-channel-config-update template name 'create-system-channel-config-update--TheConsortium--Nevergreen' undefined
```

FYI- My Nevergreen peers are not up and running, is that why I'm facing this issue? I'm unsure if that's the issue.

can you help me here a little?

**Comment by raftAtGit** [comment]
thanks for the nice words :)

himm, `peer-org-flow` is not tested against `cross-cluster` setup actually. apparently some modifications are required there.

try adding `Nevergreen` and `Atlantis` peer orgs temporarily to `crypto-config.yaml` before running `peer-org-flow`. this will possibly workaround that error.

**Comment by raftAtGit** [comment]
@Shubham-koli just released the necessary changes for adding peer organizations to cross-cluster network. A [sample](https://github.com/APGGroeiFabriek/PIVT/blob/master/README.md#cross-cluster-raft-orderer-network) is also provided.

Note, this requires Helm 2.16+

Cheers :)

**Comment by Shubham-koli** [comment]
Yes, I just saw it!
Thank you so much @raftAtGit !!! you are single-handedly saving Hyperledger Fabric community.
I can't wait to try this!
