### ISSUE TITLE
Missing policies and ACLs in configtx.yaml

### ISSUE THREAD

**Issue by jeffywu** [APGGroeiFabriek/PIVT#4]
I noticed that ACLs and policies are missing in the configtx.yaml files in the samples. Is this intentional? I have some code that required adding the default ACLs back into configtx.yaml. I can raise a PR to add some default ACLs into these files if want.

Example here: https://github.com/jeffywu/PIVT/blob/other-changes/fabric-kube/samples/simple/configtx.yaml

**Comment by raftAtGit** [comment]
Thanks, policies are fixed in master branch. In general all warning are cleared.
