### ISSUE TITLE
create-system-channel-config-update--SecondConsortium--Karga' undefined

### ISSUE THREAD

**Issue by mohdabusaif** [APGGroeiFabriek/PIVT#45]
Hi Raft,

I'm trying to add a new peer organizations to my RAFT TLS network. And I'm facing an issue with the below command to create the organization peer:

helm template peer-org-flow/ -f samples/scaled-raft-tls/configtx.yaml -f samples/scaled-raft-tls/crypto-config.yaml -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/hostAliases.yaml | argo submit - --watch

error:

2020/04/21 20:59:39 Failed to submit workflow: templates.peer-orgs.steps[0].consortiums templates.consortiums.steps[0].SecondConsortium templates.consortium--SecondConsortium.steps[0].consortium-org--Karga templates.consortium-org--SecondConsortium--Karga.steps[1].add-org-to-consortium templates.add-org-to-consortium--SecondConsortium--Karga.steps[0].create-system-channel-config-update template name 'create-system-channel-config-update--SecondConsortium--Karga' undefined

Note: I've changed the [concat] function in the peerorg-workflow.yaml file as the sample below:

{{- range $orgName := concat $channel.orgs (default list $channel.externalOrgs) }} --> to
{{- range $orgName := $channel.orgs | (default list $channel.externalOrgs) }}

HLF version = 2.1.0
OS = "Linux Mint 19.2 Tina"

**Comment by raftAtGit** [comment]
are you following the provided extending cross-cluster sample or doing on your own?

anyway, `consortium` part of the `peer-org-flow` requires, `PeerOrgs` + `ExternalPeerOrgs` in `crypto-config.yaml` includes all the peer orgs in the consortiums.

about your change, not sure if it does the same thing

**Comment by mohdabusaif** [comment]
I'm not using the cross-cluster sample.
I'm using the provided Scaled-up Raft network with TLS sample.
I've checked the peer-org-flow requires, PeerOrgs + ExternalPeerOrgs in crypto-config.yaml files and it seems it has the required configurations.

**Comment by raftAtGit** [comment]
himm, does it still not working with a fresh clone? I mean without the change you had made?

**Comment by mohdabusaif** [comment]
Which change do you mean? 
You mean to try it using HLF 1.4.5?
Or changing the yaml file (contact with | )? --> without this change change it won't work.
tlsEnabled: true --> I'm back building a RAFT TLS network.

Scaled-up Raft network with TLS it is working fine as per the guideline instructions, but the issue happens when you try to add a new peer organization. 
After many hours of investigating and checking the issues, as I mentioned above the first change was the concat in peerorg-workflow.yaml

**Comment by raftAtGit** [comment]
I meant the change you mentioned in the first message:
```
{{- range $orgName := concat $channel.orgs (default list $channel.externalOrgs) }} --> to
{{- range $orgName := $channel.orgs | (default list $channel.externalOrgs) }}
```
anyway, I just checked it and it runs fine here. I added new peer organizations to the `scaled-raft-tls` sample with just following the instructions in the readme.

**Comment by mohdabusaif** [comment]
I checked out (2nd minio link fix) commit and it is working fine. but i noticed that the orderers keeps crashing, describe pod shows this warning:

Warning  FailedScheduling  7m58s (x2 over 7m58s)  default-scheduler    pod has unbound immediate PersistentVolumeClaims

while all pvc's are created and is bound status.

**Comment by raftAtGit** [comment]
what is in the orderer logs?

**Comment by mohdabusaif** [comment]
Never mind. it worked fine finally, i pulled the project again and checked it out to the same commit I had mentioned in the previous comment, changed the below parameters:
*fabric-kube/samples/scaled-raft-tls/network.yaml:
tlsEnabled: ture
useActualDomains: true

*change the hyperledgerversion --> 2.1.0
change the hlf-kube/templates/ca-deployment.yaml/{{ $.Values.hyperledgerVersion }}
change hlf-kube/templates/ca-deployment.yaml/{{ $.Values.hyperledgerVersion }}  --> latest
change storageclass to your sc name, "default" won't work.

new peers and orderers added successfully.
Many thanks for your support. I'll check the cross cluster and I'll keep you updated.

**Comment by mohdabusaif** [comment]
Before going to the cross cluster netwroks, i tried to test the chain codes on both (simple and scaled raft with TLS networks). But it didn't work.
I noticed that workflows are in status pending, when i do the below command:
argo logs --follow --workflow wf_name
it doesn't retrieve any logs.

argo version --> argo: v2.4.1

**Comment by raftAtGit** [comment]
try `kubectl describe <argo flow name>`

**Comment by mohdabusaif** [comment]
it shows like the attached file, i've checked it it looks fine except the Finished At, Started At and the events
[wf.txt](https://github.com/APGGroeiFabriek/PIVT/files/4515455/wf.txt)

**Comment by raftAtGit** [comment]
himm, I've seen this a few times. some Argo bug I believe.

try deleting the Argo pod, it will be restarted. you might also want to check the Argo pod's logs first

**Comment by mohdabusaif** [comment]
There are no pods under the Argo namespace at all! only the channel and chaincode workflows (in pending status)

**Comment by raftAtGit** [comment]
how is it possible? maybe deployed to another namespace?

otherwise, there is a problem with your Argo deployment

**Comment by mohdabusaif** [comment]
Yes, you were right my friend, it was an issue in the Argo deployment.
Many thanks for your efforts.
