### ISSUE TITLE
Add peer org to scaled-raft-no-tls peer pod unschedulable

### ISSUE THREAD

**Issue by kudligi** [APGGroeiFabriek/PIVT#49]
When i try to follow the procedure to add a new organization. 

On running helm upgrade the ca pod comes up fine for the new org but the peer pod is always **unschedulable** / **pending.**

On the ggogle cloud console it says Reason pod is unschedulable is:
'Cannot schedule pods: pod has unbound immediate PersistentVolumeClaims (repeated times). '

the logs for that peer pod is empty.

Also on the console out i get UPGRADE FAILED .... 

Am i missing something?

**Comment by LudoNieuw** [comment]
Hi there, can you share a describe of the peer pod?

Best,

Ludo

Op ma 11 mei 2020 om 16:17 schreef nihal kudligi <notifications@github.com>

**Comment by kudligi** [comment]
`$ `kubectl` describe pod hlf-peer--nike--peer0-0 
Name:           hlf-peer--nike--peer0-0
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=hlf-peer--nike--peer0
                controller-revision-hash=hlf-peer--nike--peer0-f95858b89
                name=hlf-peer
                org=hlf-peer--nike
                statefulset.kubernetes.io/pod-name=hlf-peer--nike--peer0-0
Annotations:    kubernetes.io/limit-ranger: LimitRanger plugin set: cpu request for container peer; cpu request for container couchdb
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/hlf-peer--nike--peer0
Containers:
  peer:
    Image:      hyperledger/fabric-peer:1.4.5
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      peer node start
    Requests:
      cpu:  100m
    Environment:
      CORE_PEER_ID:                                    peer0.nike.com
      CORE_PEER_ADDRESS:                               peer0.nike.com:7051
      CORE_PEER_LISTENADDRESS:                         0.0.0.0:7051
      CORE_PEER_CHAINCODELISTENADDRESS:                0.0.0.0:7052
      CORE_PEER_GOSSIP_BOOTSTRAP:                      peer0.nike.com:7051
      CORE_PEER_GOSSIP_EXTERNALENDPOINT:               peer0.nike.com:7051
      CORE_PEER_LOCALMSPID:                            NikeMSP
      CORE_VM_ENDPOINT:                                unix:///host/var/run/docker.sock
      FABRIC_LOGGING_SPEC:                             info
      CORE_PEER_TLS_ENABLED:                           false
      CORE_PEER_GOSSIP_USELEADERELECTION:              true
      CORE_PEER_GOSSIP_ORGLEADER:                      false
      CORE_PEER_PROFILE_ENABLED:                       true
      CORE_PEER_ADDRESSAUTODETECT:                     true
      CORE_PEER_TLS_CERT_FILE:                         /etc/hyperledger/fabric/tls/server.crt
      CORE_PEER_TLS_KEY_FILE:                          /etc/hyperledger/fabric/tls/server.key
      CORE_PEER_TLS_ROOTCERT_FILE:                     /etc/hyperledger/fabric/tls/ca.crt
      CORE_CHAINCODE_LOGGING_LEVEL:                    info
      CORE_CHAINCODE_LOGGING_SHIM:                     info
      CORE_VM_DOCKER_ATTACHSTDOUT:                     true
      CORE_LEDGER_STATE_STATEDATABASE:                 CouchDB
      CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS:  localhost:5984
      CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME:        
      CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD:        
      HFC_LOGGING:                                     {"info":"console"}
      GRPC_VERBOSITY:                                  DEBUG
      GRPC_TRACE:                                      all
    Mounts:
      /chaincode/very-simple from chaincode-very-simple (rw)
      /etc/hyperledger/fabric/admin-msp/ from peer-admin-msp (rw)
      /etc/hyperledger/fabric/msp/ from peer-msp (rw)
      /etc/hyperledger/fabric/tls/ from peer-tls (rw)
      /host/var/run/docker.sock from dockersocket (rw)
      /var/hyperledger/production/ from peer-disk (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bs7z6 (ro)
  couchdb:
    Image:      hyperledger/fabric-couchdb:0.4.15
    Port:       <none>
    Host Port:  <none>
    Requests:
      cpu:  100m
    Environment:
      COUCHDB_USER:      
      COUCHDB_PASSWORD:  
    Mounts:
      /opt/couchdb/data/ from couchdb-disk (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bs7z6 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  peer-disk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  peer-disk-hlf-peer--nike--peer0-0
    ReadOnly:   false
  couchdb-disk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  couchdb-disk-hlf-peer--nike--peer0-0
    ReadOnly:   false
  rsync-disk:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  dockersocket:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  Socket
  peer-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hlf-peer--nike--peer0-tls
    Optional:    false
  peer-msp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hlf-peer--nike--peer0-msp
    Optional:    false
  peer-admin-msp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hlf-peer--nike--admin-msp
    Optional:    false
  chaincode-very-simple:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      hlf-chaincode--very-simple
    Optional:  false
  default-token-bs7z6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-bs7z6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  80s (x14 over 19m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 7 times)
`

**Comment by raftAtGit** [comment]
you need to set the `persistence.storageClass` accordingly:
https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/hlf-kube/values.yaml#L22

**Comment by kudligi** [comment]
Thanks a lot. That solved the problem.
