### ISSUE TITLE
Getting error while  create the channels on Scaled-up Raft network with TLS

### ISSUE THREAD

**Issue by abhisamant7** [APGGroeiFabriek/PIVT#50]
Hi,

I am getting error while  create the channels on Scaled-up Raft network with TLS. I followed all step and  tried to the command "helm upgrade hlf-kube `./hlf-kube -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/crypto-config.yaml -f samples/scaled-raft-tls/hostAliases.yaml "`, however getting error as 
```
ERRO[0000] Create request is failed. Error: the server could not find the requested resource (post workflows.argoproj.io) 
2020/05/17 05:12:41 Failed to submit workflow: the server could not find the requested resource (post workflows.argoproj.io)
```

Please help me above issue.

Thanks

**Comment by LudoNieuw** [comment]
Hi there,

If I read the error, I understand that you haven’t installed argo. Can you
check? Make sure you install it before launching the project.

Best,

Ludo

Op zo 17 mei 2020 om 07:15 schreef abhisamant7 <notifications@github.com>

**Comment by abhisamant7** [comment]
Hi Ludo,

I found the issue and  install the argo with controller, However I am getting other issue now.

btw thanks for the help.

Abhi
