### ISSUE TITLE
Getting error while  launch our Raft based Fabric network 

### ISSUE THREAD

**Issue by abhisamant7** [APGGroeiFabriek/PIVT#51]
Hi,

I am getting erro as `"Error: grpc: received message larger than max (128910363 vs. 20971520)"` when give command as `"helm install ./hlf-kube --name hlf-kube -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/crypto-config.yaml "`

Could anyone help me to solve the issue as I am new to helm chart I search I lot however getting lots of different things

Thanks
Abhi

**Comment by raftAtGit** [comment]
where do you see that error?

**Comment by abhisamant7** [comment]
Hi Raft,

I am getting this error while While  launch our Raft based Fabric network in broken state using command `"helm install ./hlf-kube --name hlf-kube -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/crypto-config.yaml "`
However I want add one thing regarding this error I am trying launch our Raft based Fabric network  with different chaincode files, may be this casue issue.

**Comment by raftAtGit** [comment]
which version of helm are you using? please paste the output of this command

```
helm version
```

**Comment by abhisamant7** [comment]
Hi Raft,

Please see the output of helm version 

```
Client: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.6", GitCommit:"dd2e5695da88625b190e6b22e9542550ab503a47", GitTreeState:"clean"}

```

**Comment by raftAtGit** [comment]
weird, never saw this before.

please make sure there arent unexpected additional files especially in chaincode folders.

you may also try deleting tiller pod

**Comment by abhisamant7** [comment]
Hi Raft,

Yes it may cause issue with chaincode folder as I told I have added some file which is required in my chaincode stuff. 

Btw thanks may be its out of scope issue so I am closing this one.

Thanks for the help
