### ISSUE TITLE
Argo instantiation instructions

### ISSUE THREAD

**Issue by pimotte** [APGGroeiFabriek/PIVT#54]
When trying this out, I got the following error
```
ERRO[0000] Create request is failed. Error: the server could not find the requested resource (post workflows.argoproj.io)
```
I had not intitialized argo. When I did with the following command

```
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
```

I haven't gotten to a working state yet, so I'm not entirely sure, but perhaps we can include these commands or the addendum `(and instantiate it as in README)` to argo in the dependency list?

Edit: It looks like some permissions are also needed, running

```
kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default
```

allows me to execute

```
helm template channel-flow/ -f samples/simple/network.yaml -f samples/simple/crypto-config.yaml | argo submit - --watch
```

without any errors.

I also ran 
```
kubectl apply  -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
```
(in the default namespace), but don't know if that was necessary.

**Comment by mr-rooftop** [comment]
You're right, the correct setup of Argo is not discussed in the Repo and therefore little bit hard for Argo newbies (like me).

Everything you found out is correct and has to be done.

You can also do it in a different namespace:
```
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
```

@raftAtGit gave me this link in a previous issue:
https://github.com/argoproj/argo/blob/master/docs/getting-started.md#granting-admin-privileges

But you found out about this already on your own :)

**Comment by raftAtGit** [comment]
guys I understand the confusion for the new comers to setup the requirements. that's why we provided links to relevant pages in the [requirements](https://github.com/APGGroeiFabriek/PIVT#requirements) section.

similar issues apply to installing Helm with or without RBAC etc.

there are even newbies of Kubernetes using this repo, not familiar with `kubectl` command and asking for help.

you can imagine, providing step by step instructions for setting up and usage of each tool is out of scope of this repo. and those instructions sometimes change over time when new versions are introduced.

**Comment by pimotte** [comment]
Fair enough. The reason I made this issue is that to me this was the only thing that the other dependencies are just binaries whereas argo does need instantiation. Either rephrasing the dependency as `Argo, both Controller (installed into Kubernetes) and CLI 2.4.0+`, or also including the link to the getting started page would make this more clear.

All in all, getting it to work was very doable, so if extending the readme is out of scope, I'm good with this issue being closed.

**Comment by raftAtGit** [comment]
updated the link to point to the Argo getting started page.

this was the think I was talking about, initially it was pointing to getting started page. then page is moved or disappeared and the link was broken. then a community member noticed it and made a pull request for a working link where getting started was on top, now it moved again.. :/
