### ISSUE TITLE
Export identities from existing network crypto-config files

### ISSUE THREAD

**Issue by safitudo** [APGGroeiFabriek/PIVT#56]
The goal is to connect to peer and invoke chaincode via nodejs sdk ([fabric-sdk-node](https://hyperledger.github.io/fabric-sdk-node/release-1.4/module-fabric-network.html)), but keep getting "access denied" error
Setup: 
- using simple network configuration (samples/simple)
- connecting from peer pod (hlf-peer--atlantis--peer0-0)

Wallet structure:
=== Admin@atlantis.com
===== Admin@atlantis.com
===== hlf-ca--atlantis-557b498f8c-lvk2c-pub
===== hlf-ca--atlantis-557b498f8c-lvk2c-priv

File Admin@atlantis.com:
`{"name":"Admin@atlantis.com","mspid":"msp","roles":null,"affiliation":"","enrollmentSecret":"","enrollment":{"signingIdentity":"hlf-ca--atlantis-557b498f8c-lvk2c","identity":{"certificate":"CRT"}}}`

Tried all possible combinations of certificate & private files from peer atlantis.com from crypto-config folder. Public key generated by command `ssh-keygen -y -f priv -e -m pkcs8`

Keep getting error
`2020-06-17T12:45:17.931Z - error: [Network]: _initializeInternalChannel: Unable to initialize channel. Attempted to contact 1 Peers. Last error was Error: Channel:common Discovery error:access denied`

Wondering if there is a straightforward way to properly export identities from crypto-config.
Thanks!

**Comment by raftAtGit** [comment]
I dont have experience with wallets but the information in [this issue](https://github.com/APGGroeiFabriek/PIVT/issues/27) might help

**Comment by safitudo** [comment]
Main issue here was that we used outdated nodejs sdk, didn't enroll admin identity. 
More details posted in [issue mentioned above](https://github.com/APGGroeiFabriek/PIVT/issues/27#issuecomment-646569561)

**Comment by raftAtGit** [comment]
Cool, glad to hear to solved the issue! 👍
