### ISSUE TITLE
What does PIVT acronym mean?

### ISSUE THREAD

**Issue by sillysachin** [APGGroeiFabriek/PIVT#59]
GroeiFabriek - Means Growth Factory in dutch to english google tranlate.

I could not figure what PIVT acronym means.

**Comment by LudoNieuw** [comment]
It’s the acronym for the work-name of our product: pension infrastructure
value transfer

Op ma 22 jun. 2020 om 15:40 schreef Sachin Shekhar R <
notifications@github.com>

**Comment by sillysachin** [comment]
Thanks and Regards, :)
