### ISSUE TITLE
channel-flow : unknown field "hostAliases

### ISSUE THREAD

**Issue by mallikprojects** [APGGroeiFabriek/PIVT#6]
h
Running below command
helm template channel-flow/ -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/crypto-config.yaml -f samples/scaled-raft-tls/hostAliases.yaml | argo submit - --watch

throws the following error. 
2019/09/19 22:49:29 Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: unknown field "hostAliases"

Any idea on how to resolve this?

**Comment by raftAtGit** [comment]
your Argo version is old, is not supporting `hostAliases`. they have released 2.4.0-rc1, use that please
https://github.com/argoproj/argo/releases/tag/v2.4.0-rc1

**Comment by gWOLF3** [comment]
@mallikprojects 

if your issue has been resolved, please **/close** this issue.

**Comment by mallikprojects** [comment]
Closing this issue as latest argo version solved this
