### ISSUE TITLE
v1.4 commercial paper example: problem with instantiation

### ISSUE THREAD

**Issue by gWOLF3** [APGGroeiFabriek/PIVT#7]
**What:**

Running Hyperledger Fabric Commercial Paper Example: https://hyperledger-fabric.readthedocs.io/en/release-1.4/tutorial/commercial_paper.html#instantiate-contract

**Why:**

Commercial Paper Example is the new standard tutorial for Hyperledger Fabric 1.4 capabilities.  People would definitely use this. 

**How:** 

See: https://github.com/chain-gang/PIVT/tree/commercial-paper/fabric-kube/samples/chaincode/comm-paper

1. Added new "comm-paper" node chaincode to 'samples/chaincodes' folder. 

2. Included chaincode YAML definition to list in 'samples/simple/network.yaml' file.

What happened? 

Chaincode Installed Successfully. ✅ :
```
W
Chaincode comm-paper version 1.0 is not installed to peer
-- result is: 99
-- Chaincode comm-paper version 1.0 is not installed to peer peer0, will install..
2019-09-23 18:57:27.735 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-09-23 18:57:27.735 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
2019-09-23 18:57:27.748 UTC [chaincodeCmd] install -> INFO 003 Installed remotely response:<status:200 payload:"OK" >
```

Chaincode would not instantiate ❌ :
```
W
Chaincode comm-paper version 1.0 is not instantiated on channel private-karga-atlantis
-- result is: 99
-- Chaincode comm-paper version 1.0 is not instantiated on channel private-karga-atlantis, will check another version..
Chaincode comm-paper is not instantiated on channel private-karga-atlantis
-- result is: 99
-- Chaincode comm-paper is not instantiated on channel private-karga-atlantis, will instantiate..
2019-09-23 18:57:33.163 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-09-23 18:57:33.164 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg transaction returned with failure: Error: You've asked to invoke a function
 that does not exist:
```

The command which ran: 
```
if [ -z "$doUpgrade" ]; then 
            echo '-- Chaincode comm-paper is not instantiated on channel private-karga-atlantis, will instantiate..' 
            peer chaincode instantiate --name comm-paper --version 1.0 --lang node \
                  --channelID private-karga-atlantis --orderer hlf-orderer--groeifabriek--orderer0:7050 \
                  --policy "OR('KargaMSP.member','AtlantisMSP.member')" --ctor '{"Args":[""]}'
```

Any idea what could have caused this error: `You've asked to invoke a function
 that does not exist` ?

**Comment by raftAtGit** [comment]
I guess that means you are trying to invoke a constructor which doesnt exist.

_chaincode-flow_ always invokes empty constructor, as can be seen in your above message _--ctor '{"Args":[""]}_ 

we never used a constructor for a chaincode nor required a need. but if there are use cases for that, why not? I will be glad to accept a pull request which is flexible. 

I guess the way to implement this will be like _chaincode.version_ in _chaincode-flow_ 

that is, provide a default empty _flow.instantiate.constructor_ value and allow it to be overridden by individual _network.chaincodes.name[].constructor_ values in _network.yaml_ file

**Comment by gWOLF3** [comment]
Cool, yes I found as such that the 'Commercial Paper' example does look for a constructor. 

It's a bit confusing - as yet, in the sample walkthrough documentation, it want to be instantiated with `-c '{"Args":["org.papernet.commercialpaper:instantiate"]}'`
source: https://github.com/hyperledger/fabric-samples/tree/release-1.4/commercial-paper

However, in the actual papercontract.js, it says this chaincode need not be instantiated 😕 :
```
    /**
     * Instantiate to perform any setup of the ledger that might be required.
     * @param {Context} ctx the transaction context
     */
    async instantiate(ctx) {
        // No implementation required with this example
        // It could be where data migration is performed, if necessary
        console.log('Instantiate the contract');
    }
```
source: https://github.com/hyperledger/fabric-samples/blob/release-1.4/commercial-paper/organization/magnetocorp/contract/lib/papercontract.js

**Comment by gWOLF3** [comment]
Also, on a side note, do you like this?: https://chain-gang.github.io/PIVT/#/ 

I was playing around with redoing the docs a bit and making it look a bit more modern. I used docsify with coversheet, will sharpen it up and submit PR if you are interested. 

PS: I did remove an Accenture brand reference in the first paragraph since I am trying to push for my employer to adopt this framework on a project. They were pushing back because of this and think maybe it would be better to include things of this kind in Wiki vs front page README. 

Anyways, LMK! Thanks

**Comment by raftAtGit** [comment]
well, I'm not much fluent in _javascript_ but as you have noticed, in the sample, chaincode is instantiated with a constructor:

`peer chaincode instantiate -n papercontract -v 0 -l node -c '{"Args": "org.papernet.commercialpaper:instantiate"]}' `

**Comment by raftAtGit** [comment]
> Also, on a side note, do you like this?: https://chain-gang.github.io/PIVT/#/
> 
> PS: I did remove an Accenture brand reference in the first paragraph since I am trying to push for my employer to adopt this framework on a project. They were pushing back because of this and think maybe it would be better to include things of this kind in Wiki vs front page README.

I would say, why?

**Comment by gWOLF3** [comment]
Cool,

I have implemented this now, and tested that it is working. 

(optional constructor value)
https://github.com/chain-gang/PIVT/pull/3/commits/4ebb6170f336ec55d32ab40ebffca6ef4e0d1ca6

Let me know if you would accept this as a PR.

**Comment by gWOLF3** [comment]
Closing this issue now.

**Comment by raftAtGit** [comment]
great, thanks! 
can you also please modify one of the chaincode samples to use constructor args?

**Comment by gWOLF3** [comment]
Sure, you mean just add constructor arg as empty constructor as a test? 

Or do you should I modify the chaincode slightly for one of the examples so that it will accept an optional constructor?

The optional constructor value is implemented exactly the same way as version, as you suggested.

**Comment by raftAtGit** [comment]
It would be great if you modify the chaincode to accept a constructor arg

**Comment by gWOLF3** [comment]
Yes, I will do this and submit a PR
