### ISSUE TITLE
Peer for orgs nort creating  with all sample

### ISSUE THREAD

**Issue by abhisamant7** [APGGroeiFabriek/PIVT#73]
Hi All,

I am trying to launch the simple Network using command `"helm install ./hlf-kube --name hlf-kube -f samples/simple/network.yaml -f samples/simple/crypto-config.yaml"` , however peers not creating for all orgs and when I used command "kubectl get pod --watch" to watch all pods running it showing only below 
![Screenshot from 2020-08-10 19-46-15](https://user-images.githubusercontent.com/21276072/89792516-49c20d00-db42-11ea-94cf-a55794ced22d.png)
Please hemp me what is I am doing wrong or there is issue.

please see below details of hyperledger 
peer version 
peer:
 Version: 1.4.2
 Commit SHA: c6cc550
 Go version: go1.11.5
 OS/Arch: linux/amd64
 Chaincode:
  Base Image Version: 0.4.15
  Base Docker Namespace: hyperledger
  Base Docker Label: org.hyperledger.fabric
  Docker Namespace: hyperledger

cryptogen:
 Version: 1.4.2
 Commit SHA: c6cc550
 Go version: go1.11.5
 OS/Arch: linux/amd64

Thanks in Advance

**Comment by raftAtGit** [comment]
himm, according to your screenshot, peer `StatefulSets` are not created. can you please verify:
```
kubectl get statefulset
```
if they are not really there, are you sure `peer.launchPods` is true?
https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/hlf-kube/templates/peer-statefulset.yaml#L1

**Comment by abhisamant7** [comment]
Hi Raft,

I couldn't see the peers using command` "kubectl get statefulset"`. Also how to check` peer.launchPods` as true or not?

Thanks
Abhi

**Comment by raftAtGit** [comment]
here:
https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/hlf-kube/values.yaml#L43

if that's true, check peer counts in crypto-config.yaml file
https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/samples/simple/crypto-config.yaml#L21

are you sure this is a fresh clone?

**Comment by abhisamant7** [comment]
Hi Raft ,

yes I took fresh branch also I check the value.yaml file in that under peer` launchPods:true`.

Thanks 
Abhijeet

**Comment by raftAtGit** [comment]
no clue then actually, it should just work

**Comment by abhisamant7** [comment]
Hi Raft,

Thanks for help and your comment, I have resolved it I think there is issue with my k8s cluster so I have delete it and create it again. After that its working fine.

Thanks 
Abhi
