### ISSUE TITLE
Argo workflow not running

### ISSUE THREAD

**Issue by kumar-shantanu** [APGGroeiFabriek/PIVT#74]
I am running the simple one node orderer install and all of the pods are running fine using the helm install command. When I run the argo  submit command, the pod is always in the initializing state, something like this, 
**hlf-channels-5s77m-3749709284          0/2     Init:0/1   0          2m55s**

When I describe the pod it seems like it's not able to mount the some volumes,

Warning  FailedMount  5m17s (x4 over 5m20s)  kubelet, ip-10-52-2-137.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "peer-atlantis-msp" : secret "hlf-peer--atlantis--msp" not found
  Warning  FailedMount  5m17s (x4 over 5m20s)  kubelet, ip-10-52-2-137.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "peer-nevergreen-msp" : secret "hlf-peer--nevergreen--msp" not found
  Warning  FailedMount  5m17s (x4 over 5m20s)  kubelet, ip-10-52-2-137.eu-west-1.compute.internal  MountVolume.SetUp failed for volume "hlf-configtx" : secret "hlf-configtx.yaml" not found

Can you please suggest if what might be causing it?

**Comment by raftAtGit** [comment]
this is weird. first check please if mentioned secrets are in place. for example `hlf-peer--atlantis--msp`

**Comment by kumar-shantanu** [comment]
Yeah, it's there. One thing I didn't mention above is that I installed this helm chart in a namespace called fabric, does it needs to be installed in the default namespace?

➜  ~ kubectl get secrets -n fabric
NAME                                      TYPE                                  DATA   AGE
hlf-peer--atlantis--admin-msp             Opaque                                6      12h
hlf-peer--atlantis--msp                   Opaque                                4      12h

**Comment by raftAtGit** [comment]
then you also need to run argo flows in that namespace

**Comment by kumar-shantanu** [comment]
@raftAtGit suggestion worked, closing the ticket.
