### ISSUE TITLE
Getting error while create the channels on all samples type

### ISSUE THREAD

**Issue by abhisamant7** [APGGroeiFabriek/PIVT#75]
Hi,

I am getting error while create the channels on Scaled-up Raft network with TLS. I followed all step and tried to the command "helm upgrade hlf-kube ./hlf-kube -f samples/scaled-raft-tls/network.yaml -f samples/scaled-raft-tls/crypto-config.yaml -f samples/scaled-raft-tls/hostAliases.yaml ", however getting error. 

Please find attached error logs 

![Screenshot from 2020-08-13 11-12-21](https://user-images.githubusercontent.com/21276072/90098584-32f40400-dd56-11ea-9443-453104b60d35.png)

Please help me to solve the issue.

Thanks 
Abhijeet

**Comment by raftAtGit** [comment]
that error means, orderer nodes are not ready for serving any requests. which typically happens when they couldnt elect a leader.

check your orderer logs, especially first one

**Comment by abhisamant7** [comment]
Hi Raft,

Thanks for reply. I have checked it logs of orderer. its look like below 

`2020-08-13 09:37:55.887 UTC [msp] getPemMaterialFromDir -> WARN 001 Failed reading file /etc/hyperledger/fabric/msp/admincerts/cert.pem: no pem content for file /etc/hyperledger/fabric/msp/admincerts/cert.pem
`
Why couldn't get the pem file I follow same step as mentioned. [PIVT](https://github.com/APGGroeiFabriek/PIVT)

Please advise What I am doing wrong.

Thanks

**Comment by LudoNieuw** [comment]
There might be an issue with the orderers, I had this too not long ago, and
there was something with the orderers. I wasn’t able to fix that issue,
though. For my case, I’m expecting some issues with the host VMs of the
cluster but wasn’t able to prove that (running aks)

Check logs of orderers.  Especially orderer-0. Try to keep some time
between helm install network and the channel flow.

Op do 13 aug. 2020 om 07:46 schreef abhisamant7 <notifications@github.com>

**Comment by raftAtGit** [comment]
@abhisamant7 that warning is irrelevant and harmless, see this [FAQ](https://github.com/APGGroeiFabriek/PIVT/blob/master/FAQ.md#what-are-those-no-pem-content-for-file-warnings)

As @LudoNieuw suggested, check logs of orderers.  Especially orderer-0. Try to keep some time
between helm install network and the channel flow.

**Comment by abhisamant7** [comment]
Hi,

I deleted previous setup and done new setup however getting different error in orderer logs as below.

`Failed reading file /var/hyperledger/orderer/msp/admincerts/cert.pem: no pem content for file /var/hyperledger/orderer/msp/admincerts/cert.pem

Could you please suggest me what is issue with it.

Thanks
Abhi
`

**Comment by raftAtGit** [comment]
as mentioned above,  that warning is irrelevant and harmless, see this [FAQ](https://github.com/APGGroeiFabriek/PIVT/blob/master/FAQ.md#what-are-those-no-pem-content-for-file-warnings)

**Comment by abhisamant7** [comment]
Hi Raft,

I have restart whole procedure and now I am getting error as below 

![Screenshot from 2020-08-18 12-16-34](https://user-images.githubusercontent.com/21276072/90479682-ad54c780-e14c-11ea-94fc-6fc116cc9032.png)

Please suggest how can resolve it.

Thanks in Advance

**Comment by raftAtGit** [comment]
which `Fabric` and `cryptogen` version is that?

**Comment by abhisamant7** [comment]
Both are  Version: 1.4.6

**Comment by raftAtGit** [comment]
you are using simple solo orderer sample, I guess?

what is the output of this command:
```
tree samples/simple/crypto-config/peerOrganizations/aptalkarga.tr/msp/
```

**Comment by abhisamant7** [comment]
Please see below screen shot

![Screenshot from 2020-08-18 17-15-53](https://user-images.githubusercontent.com/21276072/90509156-81e6d280-e176-11ea-8409-69d98c879dc6.png)

**Comment by raftAtGit** [comment]
and what is the output of this command:
```
kubectl get secret hlf-peer--karga--admin-msp -o yaml
```

**Comment by raftAtGit** [comment]
@LudoNieuw and @abhisamant7 

regarding the first mentioned issue [above](https://github.com/APGGroeiFabriek/PIVT/issues/75#issue-678170367), I'm rechecking it and trying locally, there is no issue actually. 

This means orderer is not ready, most possibly they couldnt elect a leader
```
Got status: &{SERVICE_UNAVAILABLE}
```


But then there is this log, meaning orderer finally is ready and responded and channel is created.
```
Received block: 0
```

**Comment by abhisamant7** [comment]
Hi @LudoNieuw,

Yes you are right however I am not getting output as mention in the screenshot in readme. but I am getting error while creating the channel.

Let me explain how I have setup it.
I have  installed Hyperledger fabric using  command `curl -sSL http://bit.ly/2ysbOFE | bash -s 1.4.6` and copy bin folder from fabric-sample using `cp fabric-samples/bin/*    /usr/local/bin` . 
is that above setup giving issue?

Please let me know what is error I am doing here.

**Comment by abhisamant7** [comment]
> ```
> kubectl get secret hlf-peer--karga--admin-msp -o yaml
> ```
```

apiVersion: v1
data:
  admincert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJakNDQWNpZ0F3SUJBZ0lSQUs4YnI3bVRveXRXaWpFSzBoaGpPbVl3Q2dZSUtvWkl6ajBFQXdJd2JURUwKTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhGakFVQmdOVkJBY1REVk5oYmlCRwpjbUZ1WTJselkyOHhGakFVQmdOVkJBb1REV0Z3ZEdGc2EyRnlaMkV1ZEhJeEdUQVhCZ05WQkFNVEVHTmhMbUZ3CmRHRnNhMkZ5WjJFdWRISXdIaGNOTWpBd09ERTRNVGcxTURBd1doY05NekF3T0RFMk1UZzFNREF3V2pCcE1Rc3cKQ1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0JNS1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ4TU5VMkZ1SUVaeQpZVzVqYVhOamJ6RVBNQTBHQTFVRUN4TUdZMnhwWlc1ME1Sd3dHZ1lEVlFRRERCTkJaRzFwYmtCaGNIUmhiR3RoCmNtZGhMblJ5TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWmlXTEUwbkdqSXRZMUt6cnpKRkEKWXFkTDVtUVorbHRVVWdhNTI2akg4UFV6dmVNcXc4YzU2KzEvNk1NM0htRWdTZ2xGc2lTNjRraVdZQ2dVdEYyNQpmNk5OTUVzd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdLd1lEVlIwakJDUXdJb0FnCjI3TkNYWkIwbkZjQlB0RnBGaWRXS1paZEV1S2k5cHFQTnV2VTZvenZiTk13Q2dZSUtvWkl6ajBFQXdJRFNBQXcKUlFJaEFNdlM1UHVzWEE1NElGc054TEV0cnd3OHFLaDhBUm9GM1orZ2pxWDJsWkhDQWlBMlB3MnVpYWYyS0RpbApoaThZdlBuRDVKeElaZC9GcldFZlJuS21PNjAreXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  cacert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNSRENDQWV1Z0F3SUJBZ0lRUURTa0t0akpwUDM1R0F2SGRmOFIvakFLQmdncWhrak9QUVFEQWpCdE1Rc3cKQ1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0JNS1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ4TU5VMkZ1SUVaeQpZVzVqYVhOamJ6RVdNQlFHQTFVRUNoTU5ZWEIwWVd4cllYSm5ZUzUwY2pFWk1CY0dBMVVFQXhNUVkyRXVZWEIwCllXeHJZWEpuWVM1MGNqQWVGdzB5TURBNE1UZ3hPRFV3TURCYUZ3MHpNREE0TVRZeE9EVXdNREJhTUcweEN6QUoKQmdOVkJBWVRBbFZUTVJNd0VRWURWUVFJRXdwRFlXeHBabTl5Ym1saE1SWXdGQVlEVlFRSEV3MVRZVzRnUm5KaApibU5wYzJOdk1SWXdGQVlEVlFRS0V3MWhjSFJoYkd0aGNtZGhMblJ5TVJrd0Z3WURWUVFERXhCallTNWhjSFJoCmJHdGhjbWRoTG5SeU1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUJtakVVckpHZ0tuZERCL3YKWHFzMUtRSHVjQi9Da01LZ2JlMjFYTmVQc1FNL0lqb21XY0I4UE5WVVJIU3puNHVkbEQ3eTRib1hjbkxub0NUMAozY3ZNRGFOdE1Hc3dEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUNCZ2dyCkJnRUZCUWNEQVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUNrR0ExVWREZ1FpQkNEYnMwSmRrSFNjVndFKzBXa1cKSjFZcGxsMFM0cUwybW84MjY5VHFqTzlzMHpBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlBZTc0RWFZWFpVK3ZBTwo4L3lGSFJlSmtEVVJTY1lGWHEyckxRZStSYkloc0FJZ2VZZlFreTZzdFBiakp0S1RERXBaUTNFT2xSYStZcUFOCnQ2U1VaSVFNUTJFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNJakNDQWNpZ0F3SUJBZ0lSQUs4YnI3bVRveXRXaWpFSzBoaGpPbVl3Q2dZSUtvWkl6ajBFQXdJd2JURUwKTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhGakFVQmdOVkJBY1REVk5oYmlCRwpjbUZ1WTJselkyOHhGakFVQmdOVkJBb1REV0Z3ZEdGc2EyRnlaMkV1ZEhJeEdUQVhCZ05WQkFNVEVHTmhMbUZ3CmRHRnNhMkZ5WjJFdWRISXdIaGNOTWpBd09ERTRNVGcxTURBd1doY05NekF3T0RFMk1UZzFNREF3V2pCcE1Rc3cKQ1FZRFZRUUdFd0pWVXpFVE1CRUdBMVVFQ0JNS1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ4TU5VMkZ1SUVaeQpZVzVqYVhOamJ6RVBNQTBHQTFVRUN4TUdZMnhwWlc1ME1Sd3dHZ1lEVlFRRERCTkJaRzFwYmtCaGNIUmhiR3RoCmNtZGhMblJ5TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWmlXTEUwbkdqSXRZMUt6cnpKRkEKWXFkTDVtUVorbHRVVWdhNTI2akg4UFV6dmVNcXc4YzU2KzEvNk1NM0htRWdTZ2xGc2lTNjRraVdZQ2dVdEYyNQpmNk5OTUVzd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdLd1lEVlIwakJDUXdJb0FnCjI3TkNYWkIwbkZjQlB0RnBGaWRXS1paZEV1S2k5cHFQTnV2VTZvenZiTk13Q2dZSUtvWkl6ajBFQXdJRFNBQXcKUlFJaEFNdlM1UHVzWEE1NElGc054TEV0cnd3OHFLaDhBUm9GM1orZ2pxWDJsWkhDQWlBMlB3MnVpYWYyS0RpbApoaThZdlBuRDVKeElaZC9GcldFZlJuS21PNjAreXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  config.yaml: ""
  key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ3A5OEliVC82dkRPNlViN28KUW1NWXp6K0J2ZUhmMVVGVVVHT2s4UVRzbDhhaFJBTkNBQVJtSllzVFNjYU1pMWpVck92TWtVQmlwMHZtWkJuNgpXMVJTQnJuYnFNZnc5VE85NHlyRHh6bnI3WC9vd3pjZVlTQktDVVd5SkxyaVNKWmdLQlMwWGJsLwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  tlscacert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNTekNDQWZLZ0F3SUJBZ0lSQVAzVzBkSzZkOVJTY3BMOFo5Z01Ib293Q2dZSUtvWkl6ajBFQXdJd2NERUwKTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhGakFVQmdOVkJBY1REVk5oYmlCRwpjbUZ1WTJselkyOHhGakFVQmdOVkJBb1REV0Z3ZEdGc2EyRnlaMkV1ZEhJeEhEQWFCZ05WQkFNVEUzUnNjMk5oCkxtRndkR0ZzYTJGeVoyRXVkSEl3SGhjTk1qQXdPREU0TVRnMU1EQXdXaGNOTXpBd09ERTJNVGcxTURBd1dqQncKTVFzd0NRWURWUVFHRXdKVlV6RVRNQkVHQTFVRUNCTUtRMkZzYVdadmNtNXBZVEVXTUJRR0ExVUVCeE1OVTJGdQpJRVp5WVc1amFYTmpiekVXTUJRR0ExVUVDaE1OWVhCMFlXeHJZWEpuWVM1MGNqRWNNQm9HQTFVRUF4TVRkR3h6ClkyRXVZWEIwWVd4cllYSm5ZUzUwY2pCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkpieW5tTUoKZm41VEljOStTc2RsZVN4L1d4NHU5RE9MbVg0RjhlZS92d09zS2dSRlF1TG5KUzVRODJ1dXRveHlzRWZ2cGwyKwpjRFRTVVZMVzZNU3dPV3lqYlRCck1BNEdBMVVkRHdFQi93UUVBd0lCcGpBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGCkJRY0RBZ1lJS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFwQmdOVkhRNEVJZ1FnQklNQ0EycHIKS012SHEvR0ZoNWMxOElscldsL2x1amhnMGdCNThGWmpSZTh3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnWDlReAplbTEyY3VydkdYMWEvM1lmNjNOeDBjR3pYNWJmcGNyL205TzFsc1FDSUdjcHE3TmxJZmJpSGFyei9sOEZUNjNRCkY0REVHQ3g4dDFPd2VkcTFGc3puCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  creationTimestamp: "2020-08-18T18:59:57Z"
  labels:
    orgName: Karga
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:admincert.pem: {}
        f:cacert.pem: {}
        f:cert.pem: {}
        f:config.yaml: {}
        f:key.pem: {}
        f:tlscacert.pem: {}
      f:metadata:
        f:labels:
          .: {}
          f:orgName: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-08-18T18:59:57Z"
  name: hlf-peer--karga--admin-msp
  namespace: default
  resourceVersion: "21996"
  selfLink: /api/v1/namespaces/default/secrets/hlf-peer--karga--admin-msp
  uid: ebf16d69-fa20-459a-8cac-a3e7e9a625f8
type: Opaque

```

**Comment by raftAtGit** [comment]
himm, `config.yaml` should not be empty in that secret. not sure what is going on there.

what is the output of this command?
```
tree hlf-kube/crypto-config/peerOrganizations/aptalkarga.tr/msp/
```

**Comment by abhisamant7** [comment]
Please see the attached screen shot of output

![Screenshot from 2020-08-19 01-37-33](https://user-images.githubusercontent.com/21276072/90560365-9c439f00-e1bc-11ea-874a-9c38ba02dab5.png)

**Comment by raftAtGit** [comment]
okay, `config.yaml` is in the folder but it's not in the `hlf-peer--karga--admin-msp` secret. I dont know what is going on there. I cannot see a reason for this..

I would suggest, tear down everything and start over, using `init.sh` script.

**Comment by abhisamant7** [comment]
Hi Raft,

I restarted many time however its show same issue as mentioned above. is there issue with config file or  cryptogen tool?

**Comment by raftAtGit** [comment]
cryptogen tool is okay, it creates the `config.yaml` file, but the file doesnt go into relevant secret.

you are using latest master branch of our repo, right? not the release 0.7 branch?

**Comment by abhisamant7** [comment]
Yes I am using latest one I cloned master one only

**Comment by raftAtGit** [comment]
not a good idea I guess. the whole idea of this repo is automation.

just one more check, what is the output of this command:
```
tree hlf-kube/crypto-config/peerOrganizations/aptalkarga.tr/users/Admin@aptalkarga.tr/msp/
```

**Comment by abhisamant7** [comment]
Hi Raft ,

As you suggest I again cloned master repo and try with step as mentioned, however getting same issue.

`tree hlf-kube/crypto-config/peerOrganizations/aptalkarga.tr/users/Admin@aptalkarga.tr/msp/
`
Please see the attached logs of above command.
![Screenshot from 2020-08-19 14-45-00](https://user-images.githubusercontent.com/21276072/90616227-cf247c00-e22a-11ea-9199-dd8dcab74f10.png)

**Comment by abhisamant7** [comment]
> Hi @LudoNieuw,
> 
> Yes you are right however I am not getting output as mention in the screenshot in readme. but I am getting error while creating the channel.
> 
> Let me explain how I have setup it.
> I have installed Hyperledger fabric using command `curl -sSL http://bit.ly/2ysbOFE | bash -s 1.4.6` and copy bin folder from fabric-sample using `cp fabric-samples/bin/* /usr/local/bin` .
> is that above setup giving issue?
> 
> Please let me know what is error I am doing here.

@raftAtGit  can you check it is it right way to install HLF into EC2 instance where we using the command?

**Comment by raftAtGit** [comment]
these screenshots are different from the previous ones, in these ones, admincerts folder not empty, but it was in the previous one

I guess there is a confusion in your PATH variable. double check what version of `cryptogen` you are using with the command 
```cryptogen version```

the folder structure should be like this:
![image](https://user-images.githubusercontent.com/4981475/90617562-1dc41d00-e20f-11ea-9a6b-d2d2cb658c35.png)

> @raftAtGit can you check it is it right way to install HLF into EC2 instance where we using the command?

sorry but this is not a Fabric/bash basics forum.

but I guess this is not correct:
> cp fabric-samples/bin/* /usr/local/bin

it should be
```
cp ./bin/* /usr/local/bin
```

**Comment by abhisamant7** [comment]
I am also get confused let me close it and try it from the starting.

Thanks Raft for your help and support 

Regards,
Abhijeet

**Comment by abhisamant7** [comment]
> `cryptogen version`

My cryptogen version is 1.4.6

**Comment by abhisamant7** [comment]
Hi Raft,



> these screenshots are different from the previous ones, in these ones, admincerts folder not empty, but it was in the previous one
> 
> I guess there is a confusion in your PATH variable. double check what version of `cryptogen` you are using with the command
> `cryptogen version`
> 
> the folder structure should be like this:
> ![image](https://user-images.githubusercontent.com/4981475/90617562-1dc41d00-e20f-11ea-9a6b-d2d2cb658c35.png)
> 
> > @raftAtGit can you check it is it right way to install HLF into EC2 instance where we using the command?
> 
> sorry but this is not a Fabric/bash basics forum.
> 
> but I guess this is not correct:
> 
> > cp fabric-samples/bin/* /usr/local/bin
> 
> it should be
> 
> ```
> cp ./bin/* /usr/local/bin
> ```

Hi Raft,

As shown in screenshot I am getting same output however still while creating channel giving issue 

Please  find attached file 

![Screenshot from 2020-08-19 17-54-31](https://user-images.githubusercontent.com/21276072/90634486-626aab00-e245-11ea-81a5-4e34dac82ab9.png)

cryptogen version

My cryptogen version is 1.4.6

**Comment by raftAtGit** [comment]
what is failing exactly? I can see in the logs `received block 0` which means channel is actually created.

what is the status (screenshot) of overall Argo flow?

**Comment by abhisamant7** [comment]
> what is the status (screenshot) of overall Argo flow?

How to get  status (screenshot) of overall Argo flow??

**Comment by abhisamant7** [comment]
> > what is the status (screenshot) of overall Argo flow?
> How to get status (screenshot) of overall Argo flow??
> I am also not sure what is failing but when creating the channel using helm template `channel-flow/ -f samples/simple/network.yaml -f samples/simple/crypto-config.yaml | argo submit - --watch` its not creating any channel and give output of kubectl get po as 
```

NAME                                    READY   STATUS      RESTARTS   AGE
hlf-ca--atlantis-6685485f85-5dq8j       1/1     Running     0          65m
hlf-ca--karga-65fbfb9f7c-jl2jg          1/1     Running     0          65m
hlf-ca--nevergreen-77cf8b6fd4-58n6c     1/1     Running     0          65m
hlf-channels-mvvmz-2888564703           0/2     Completed   0          33m
hlf-orderer--groeifabriek--orderer0-0   1/1     Running     0          65m
hlf-peer--atlantis--peer0-0             2/2     Running     0          65m
hlf-peer--karga--peer0-0                2/2     Running     0          65m
hlf-peer--nevergreen--peer0-0           2/2     Running     0          65m

```
Thanks

**Comment by raftAtGit** [comment]
what makes you think channel is not created?

check the overall status please:
```
argo list  -> get the name of flow
argo get <flow name>
```

**Comment by abhisamant7** [comment]
Please see the attached screenshot of flow
![Screenshot from 2020-08-19 18-30-24](https://user-images.githubusercontent.com/21276072/90637831-1ec67000-e24a-11ea-8b9e-da04a9c5145d.png)

**Comment by raftAtGit** [comment]
man, you have a problem with your Argo setup. possibly service account issue. search in this repo for that or check Argo documents.

the channel creation actually completes, but Argo cannot watch to Pod.

before continuing, make sure you can successfully run a sample Argo flow from Argo documents.

**Comment by abhisamant7** [comment]
Oh my bad, I will check it however link you have shared on above for argo is not available. could you please share link which is available which help who deal first time with argo like me.

Please share link where I can do proper argo installation and setup for this project this will really appreciate. 
Thanks for all support and help Raft its really life saving help

**Comment by raftAtGit** [comment]
well, they change the link all the time :/

https://github.com/argoproj/argo/blob/master/docs/quick-start.md

**Comment by abhisamant7** [comment]
Hi Raft,

I  reinstalled  argo and the tried again however its shows pending for long time. is there issue with it?

**Comment by raftAtGit** [comment]
yes, there is an issue with it. it means there is an issue with your setup.

apologies, but again, this repo is not meant to be an Fabric/Argo/Bash help forum. you need to find your find way around these things. Google will help!

> before continuing, make sure you can successfully run a sample Argo flow from Argo documents.

**Comment by abhisamant7** [comment]
Hi Raft,

Thanks for support.

I have resolved the issue as I need to add below command while install argo controller.

`kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=default:default`
