### ISSUE TITLE
Question: How to implement Hyperledger Fabric Real-time Monitoring  using tools like with Prometheus & Grafana

### ISSUE THREAD

**Issue by abhisamant7** [APGGroeiFabriek/PIVT#78]
Hi All,

I have created successfully  Scaled-up Raft network with TLS on AWS and its running fine however I have question regarding Hyperledger Fabric Real-time Monitoring  using tools like with Prometheus & Grafana. I want to implement it however I need to understand how to configure it with this setup. If anybody have any idea how to do it could please guide me so I can also do it.

Thanks  in Advance
Abhi

**Comment by raftAtGit** [comment]
have a look at:
https://github.com/APGGroeiFabriek/PIVT/blob/master/fabric-kube/hlf-kube/templates/peer-statefulset.yaml#L339

orderer is similar

**Comment by abhisamant7** [comment]
Hi Raft,

Do you have any Document how to use Monitoring using tools like with Prometheus & Grafana?

**Comment by raftAtGit** [comment]
No, but basically you need to add scraping targets in Prometheus for Fabric components

**Comment by abhisamant7** [comment]
Hi Raft,

Could you please elaborate little more where I need to add scraping   targets in Prometheus for Fabric components?

**Comment by raftAtGit** [comment]
https://lmgtfy.com/?q=prometheus+add+scraping+targets+for+hyperledger+fabric

;)

**Comment by abhisamant7** [comment]
Thanks a lot :-)
